[project]
name = "qwen3-tts-api"
version = "0.1.0"
description = "Qwen3-TTS voice cloning & synthesis API"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi[standard]",
    "qwen-tts",
    "torch>=2.5.0,<2.6.0",
    "torchaudio>=2.5.0,<2.6.0",
    "soundfile",
    "python-multipart",
]

[tool.uv]
index-url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu121" }
torchaudio = { index = "pytorch-cu121" }
